version: 0.1
phases:
  install:
    commands:
      - npm install .
      - npm install webpack@^3.0.0 -g
      - aws s3 sync s3://$S3_KEYS/ ~/.ssh/
      - apt-get update
      - apt-get install openssh-client
      - eval "$(ssh-agent -s)"
      - ssh-add -K ~/.ssh/id_rsa
      - git clone git@github.com:Rodco/ion.git
  build:
    commands:
      - webpack -p --progress
      - aws s3 sync ./dist s3://$S3_PREFIX --acl public-read
artifacts:
  type: zip
  files:
    - package.json
