version: 0.1
phases:
  install:
    commands:
      - npm install .
      - npm install webpack@^3.0.0 -g
  build:
    commands:
      - git clone https://4dbb3d379f28da45d1b70f8168001a451b802f65@github.com/Rodco/ion.git
      - webpack -p --progress
      - aws s3 sync ./dist s3://$S3_PREFIX --acl public-read
artifacts:
  type: zip
  files:
    - package.json
